# Generated by Django 3.2 on 2021-04-26 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('issuer', models.TextField(choices=[('Vinnytsia', 'Вінниця'), ('Lutsk', 'Луцьк'), ('Dnipro', 'Дніпро'), ('Kramatorsk', 'Краматорськ'), ('Zhytomyr', 'Житомир'), ('Uzhhorod', 'Ужгород'), ('Zaporizhia', 'Запоріжжя'), ('Ivano-Frankivsk', 'Івано-Франківськ'), ('Kropyvnytskyi', 'Кропивницький'), ('Sievierodonetsk', 'Сєвєродонецьк'), ('Lviv', 'Львів'), ('Kyiv', 'Київ'), ('Sevastopol', 'Севастополь'), ('Mykolaiv', 'Миколаїв'), ('Odessa', 'Одеса'), ('Poltava', 'Полтава'), ('Rivne', 'Рівне'), ('Sumy', 'Суми'), ('Ternopil', 'Тернопіль'), ('Kharkiv', 'Харків'), ('Kherson', 'Херсон'), ('Khmelnytskyi', 'Хмельницький'), ('Cherkasy', 'Черкаси'), ('Chernivtsi', 'Чернівці'), ('Chernihiv', 'Чернігів')])),
                ('act_id', models.TextField()),
                ('title', models.TextField()),
                ('forwarded', models.BooleanField(default=False)),
                ('removed_from_source', models.BooleanField(default=False)),
                ('needs_inspection', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('issuer', 'act_id')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('url', models.TextField()),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to='acts')),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='acts.act')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
